export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_TASKS = "ADD_TO_TASKS";
//export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_TASKS = "REMOVE_FROM_TASKS";
export const CLEAR_TASKS = "CLEAR_TASKS";
export const UPDATE_TASK_QUANTITY = "UPDATE_TASK_QUANTITY";
export const TOGGLE_TASKS = "TOGGLE_TASKS";
